plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  - CONTRIBUTING.md
  - README.md
  - LICENSE.md
  - COPYING.md
  - CODE_OF_CONDUCT.md
  - CONTRIBUTING.md
  - ISSUE_TEMPLATE.md
  - PULL_REQUEST_TEMPLATE.md
# kramdown:
#   syntax_highlighter: coderay
#   syntax_highlighter_opts:
#     line_numbers: true
markdown: kramdown
kramdown:
  syntax_highlighter_opts:
    formatter: HTMLLinewise
    span:
      line_numbers: false
    block:
      line_numbers: true