plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  - CONTRIBUTING.md
  - README.md
  - LICENSE.md
  - COPYING.md
  - CODE_OF_CONDUCT.md
  - CONTRIBUTING.md
  - ISSUE_TEMPLATE.md
  - PULL_REQUEST_TEMPLATE.md

# theme: minima
# header_pages:
#   - lab1.md
# minima:
#   skin: dark
#   social_links:
#     github: kompotmalinowy
#     facebook: 404
#     instagram: 404
#     telegram: 404

markdown: kramdown
kramdown:
  syntax_highlighter: rouge
  parse_block_html: true
#   syntax_highlighter: coderay
  syntax_highlighter_opts:
#     line_numbers: true

